### ISSUE TITLE
what the variable '-activations' stand for?

### ISSUE THREAD

**Issue by lixiaosi33** [val-iisc/fast-feature-fool#2]
https://github.com/val-iisc/fast-feature-fool/blob/8988ed58e6941b948ab22a05304b2aacf78b759d/train.py#L60

what the variable '-activations' stand for?

**Comment by utsavgarg** [comment]
@lixiaosi33 it is a cost function we have defined in `https://github.com/val-iisc/fast-feature-fool/blob/master/misc/losses.py`.
