### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by ovol59** [val-iisc/fast-feature-fool#6]
Unable to download "https://www.dropbox.com/s/k4tamvdjndyvgws/preprocessed_images_224.npy?raw=1" and "https://www.dropbox.com/s/0v8pnnumbytb378/preprocessed_images_227.npy?raw=1". How should I make these files? What is the difference between 227 and 224?

**Comment by UniqueGhost** [comment]
Hi friends, how to solve this problem in the end?
